org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=25w14craftmine
archive_minecraft_version=25w14craftmine
supported_version=25w14craftmine
loader_version=0.16.12

# Mod Properties
mod_version=18.0.2
release_type=beta
mod_id=jade
maven_group=snownee.jade
archives_base_name=Jade

# Dependencies
fabric_version=0.119.8+25w14craftmine
cloth_config_version=7.0.65
# https://modrinth.com/mod/modmenu/versions
modmenu_version=14.0.0-rc.2
rei_version=9.1.504
jei_version=19.8.5.117
tr_energy_version=4.1.0
