org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
archive_minecraft_version=26.1
supported_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=26.0.5
release_type=beta
mod_id=jade
maven_group=snownee.jade
archives_base_name=Jade

# Dependencies
fabric_api_version=0.144.0+26.1
cloth_config_version=19.0.147
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.5
rei_version=20.0.811
jei_version=29.1.0.16
tr_energy_version=5.0.0
