org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

minecraft_version=1.21.9
archive_minecraft_version=1.21.9
supported_version=1.21.9
neo_version=21.9.6-beta

# Mod Properties
mod_version=20.0.3
release_type=beta
mod_id=jade
maven_group=snownee.jade
archives_base_name=Jade

# Dependencies
fabric_version=0.133.14+1.21.9
cloth_config_version=19.0.147
# https://modrinth.com/mod/modmenu/versions
modmenu_version=15.0.0-beta.3
rei_version=20.0.811
jei_version=24.0.0.2
tr_energy_version=4.1.0