modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-SA-4.0"
licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en"
issueTrackerURL = "https://github.com/Snownee/Jade/issues?q=is%3Aissue"

[[mods]]
modId = "jade"
version = "${file.jarVersion}"
displayName = "Jade"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/jade"
description = "Minecraft mod shows what you are looking at. (Hwyla fork)"
iconFile = "icon.png"
credits = "TehNut, ProfMobius, kalkafox"

[[mixins]]
config = "jade.mixins.json"

[[dependencies.jade]]
modId = "neoforge"
versionRange = "[26.2-beta, )"